# Generated by Django 4.2 on 2024-06-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chat",
            new_name="Conversation",
        ),
    ]
