# Generated by Django 4.2 on 2024-06-14 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_conversation_chat_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("character", models.CharField(max_length=100)),
                ("prompt", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="conversation",
            name="chat_history",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), default=list, size=None
            ),
        ),
    ]
