# Generated by Django 4.2 on 2024-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_systemprompt_alter_conversation_chat_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
